# 정수 인코딩
## 정수 인코딩 : sorting test

In [1]:
from collections import Counter

a = [-1, -2, -3, -1, -2]
A =Counter(a)   # 리스트 안에 숫자가 얼마나 있는지 딕셔너리{}로 체크
print(A)

print(sorted(A))    # 오름차순으로 key값만 출력(기본 : 오름차순)
print(sorted(A.items()))    # 오름차순으로 key값과 value값도 출력
print(sorted(A.items(), key = lambda x: (-x[1], x[0])))
print(sorted(A.items(), key = lambda x: (x[0], -x[1])))

Counter({-1: 2, -2: 2, -3: 1})
[-3, -2, -1]
[(-3, 1), (-2, 2), (-1, 2)]
[(-2, 2), (-1, 2), (-3, 1)]
[(-3, 1), (-2, 2), (-1, 2)]


## 정수 인코딩

In [5]:
# 어제 한 부분이지만 오늘 코드를 돌리기 위해 가져옴
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

raw_text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

# 문장 토큰화
sentences = sent_tokenize(raw_text)
print(sentences)

vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english'))

for sentence in sentences:
    # 단어 토큰화
    tokenized_sentence = word_tokenize(sentence)
    result = []
    for word in tokenized_sentence:
        word = word.lower()    # 모든 단어를 소문자화하여 단어의 개수를 줄인다
        if word not in stop_words:    # 단어 토큰화 된 결과에 대해서 불용어를 제거한다
            if len(word) > 2:    # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거한다
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0
                vocab[word] += 1    # {'barber', 1} barber가 나올수록 숫자 증가
    preprocessed_sentences.append(result)
print(preprocessed_sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']
[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [6]:
# 자주 쓰는 단어 추려내서 빈도수가 몇번인지 확인하여 많이 나오는 순으로 입력
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [7]:
# 빈도수 많은 단어 순서대로 번호 붙임
word_to_index = {}
i = 0
for (word, frequency) in vocab_sorted:    # key, value값으로 나눔
    if frequency > 1:    # 빈도수가 작은 단어는 제외
        i += 1
        word_to_index[word] = i
        
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [8]:
# 빈도수 상위 5개의 단어만 남길
vocab_size = 5

# 인덱스가 5 초과인 단어 제거
words_frequency = [word for word, index in word_to_index.items() if index >= vocab_size + 1]

for w in words_frequency:
    del word_to_index[w]    # 해당 단어에 대한 인덱스 정보를 삭제
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


## 정수 인코딩 : sentences에 있는 각 단어를 정수로 바꾸는 작업

In [9]:
#OOV : Out - Of - Vocabulary (단어 집합에 없는 단어)
word_to_index['OOV'] = len(word_to_index) + 1
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


In [10]:
# 원래 문장을 숫자로 변환
encoded_sentences = []
for sentence in preprocessed_sentences:    # 단어들의 리스트 목록에서 리스트 별로 받음 [[ , ], [ , , ]]
    encoded_sentence = []
    for word in sentence:    # 리스트 안에 단어 받음 [ , ]
        try:
            # word_to_index는 빈도수별로 단어 정리한 목록
            # word_to_index[word]를 입력하면 word의 단어가 해당되는 번호 출력
            encoded_sentence.append(word_to_index[word])    # 단어가 있으면 encoded_sentence에 입력 [1, 5]
            
        except KeyError:    # except만 하면 모든 에러에 해당되지만 여기서는 KeyError
            # 위에 문단에서 빈도수 5 이상의 단어(단어 리스트에 없는 단어)는 모드 6으로 줬는데
            # 여기서도 상위 5개 이하의 단어가 나오면 6을 입력하게 했다
            encoded_sentence.append(word_to_index['OOV'])
            
    encoded_sentences.append(encoded_sentence)    # 리스트에 입력[[1,5]]
print(encoded_sentences)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


## Counter 사용하기

In [14]:
from collections import Counter

# Counter 사용하기 전 문장 확인
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [15]:
# words = np.hstack(preprocessed_sentences)로도 수행 가능
all_words_list = sum(preprocessed_sentences, [])    # 내부 리스트 풀어줌
print(all_words_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [16]:
# 파이썬의 Counter 모듈을 이용하여 단어의 빈도수 카운트(중복 제거한다)
vocab = Counter(all_words_list)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [17]:
print(vocab['barber'])    # 'barber'라는 단어의 빈도수 출력

8


In [18]:
vocab_size = 5
vocab = vocab.most_common(vocab_size)    # 등장 빈도수가 높은 상위 5개의 단어만 저장
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [19]:
# 위의 상위 5개의 단어만 저장하는 결과는 같다
word_to_index = {}
i = 0
for (word, frequency) in vocab:
    i += 1
    word_to_index[word] = i
    
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


## NLTK의 FreqDist 사용하기

In [20]:
from nltk import FreqDist
import numpy as np

# np.hstack으로 문장 구분을 제거
np.hstack(preprocessed_sentences)

array(['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge',
       'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret',
       'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept',
       'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge',
       'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge',
       'mountain'], dtype='<U8')

In [22]:
vocab = FreqDist(np.hstack(preprocessed_sentences))
vocab

FreqDist({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, ...})

In [23]:
vocab_size = 5
vocab = vocab.most_common(vocab_size)    # 등장 빈도수가 높은 상위 5개의 단어만 저장
print(vocab)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]


In [24]:
word_to_intdex = {word[0] : index+1 for index, word in enumerate(vocab)}    # 각 단어(word[0])의 번호를 index에 맞춰서 바꿔준다
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


### enumerate 이해하기

In [25]:
test_input = ['a', 'b', 'c', 'd', 'e']
for index, value in enumerate(test_input):    # 입력의 순서대로 0부터 인덱스를 부여함
    print("value : {}, index : {}".format(value, index))

value : a, index : 0
value : b, index : 1
value : c, index : 2
value : d, index : 3
value : e, index : 4


## 케라스의 텍스트 전처리

In [26]:
from tensorflow.keras.preprocessing.text import Tokenizer

# 이건 그냥 검증
preprocessed_sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [33]:
tokenizer = Tokenizer()

# fit_on_texts() 안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성
tokenizer.fit_on_texts(preprocessed_sentences)

# fit_on_texts()가 되어 있어야 아래 함수들을 수행할 수 있다

In [34]:
# Tokenizer()라는 클래스에서 word_index를 보면 정리된 리스트 나옴
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [35]:
# Tokenizer()라는 클래스에서 word_counts(빈도수 데이터) 출력
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [36]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [37]:
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 1)    # 상위 5개 단어만 사용
tokenizer.fit_on_texts(preprocessed_sentences)

In [38]:
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [39]:
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [40]:
# 실질적으로 상위 5개 단어만 사용하는건 texts_to_sequences를 써야 적용 된다
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [41]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)

vocab_size = 5
# 인덱스가 5 초과인 단어 제거
words_frequency = [word for word, index in tokenizer.word_index.items() if index >= vocab_size + 1]
for word in words_frequency:
    del tokenizer.word_index[word]    # 해당 단어에 대한 인덱스 정보를 삭제
    del tokenizer.word_counts[word]    # 해당 단어에 대한 카운트 정보를 삭제
    
print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preprocessed_sentences))

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}
OrderedDict([('barber', 8), ('person', 3), ('huge', 5), ('secret', 6), ('kept', 4)])
[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [45]:
# 숫자 0과 OOV를 고려해서 단어 집합의 크기는 +2
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 2, oov_token='OOV')
tokenizer.fit_on_texts(preprocessed_sentences)

In [46]:
print("단어 OOV의 인덱스 : {}".format(tokenizer.word_index['OOV']))

단어 OOV의 인덱스 : 1


In [48]:
# 집합에 없는 단어는 1로, 집합에 있는 단어는 1씩 더해줬다
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


이전 과정 : 토큰화, 정제/정규화, 어간/표제어, 불용어, 정규표현식, 정수인코딩
# 패딩(Padding)
## Numpy로 패딩하기

In [49]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

preprocessed_sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [50]:
tokenizer = Tokenizer()

# fit_on_texts() 안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성
tokenizer.fit_on_texts(preprocessed_sentences)

In [51]:
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [52]:
# 문장이 가장 긴게 뭔지 출력
max_len = max(len(item) for item in encoded)
print(max_len)

7


In [53]:
# 문장의 길이를 가장 긴 문장의 길이로 맞춰줌
for sentence in encoded:    # 각 문장에 대해서
    while len(sentence) < max_len:    # max_len보다 작으면
        sentence.append(0)
        
padded_np = np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

## 케라스 전처리 도구로 패딩하기

In [54]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [55]:
padded = pad_sequences(encoded)    # 앞쪽에 0을 채움
padded

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]])

In [56]:
padded = pad_sequences(encoded, padding = 'post')    # 뒤에 0을 채움
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])